# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jdm\Desktop\labtool\lab_tool\add_color.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(300, 120)
        dialog.setMinimumSize(QtCore.QSize(300, 120))
        dialog.setMaximumSize(QtCore.QSize(300, 120))
        self.line_edit = QtWidgets.QLineEdit(dialog)
        self.line_edit.setGeometry(QtCore.QRect(90, 30, 120, 34))
        self.line_edit.setObjectName("line_edit")
        self.push_button_cancel = QtWidgets.QPushButton(dialog)
        self.push_button_cancel.setGeometry(QtCore.QRect(30, 80, 99, 30))
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.push_button_ok = QtWidgets.QPushButton(dialog)
        self.push_button_ok.setGeometry(QtCore.QRect(170, 80, 99, 30))
        self.push_button_ok.setObjectName("push_button_ok")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "新增颜色"))
        self.push_button_cancel.setText(_translate("dialog", "取消"))
        self.push_button_ok.setText(_translate("dialog", "确定"))
